// Offline helper: closes each circuit by gently flexing every straight and turn
// of its layout (regularised Levenberg-Marquardt), then writes src/solved.js.
//   node tools/solve-track.mjs [trackId ...]
import fs from 'node:fs';
import { runOps } from '../src/track.js';
import { LAYOUTS } from '../src/layouts.js';

const only = process.argv.slice(2);
const ids = Object.keys(LAYOUTS).filter((id) => !only.length || only.includes(id));
let solved = {};
try {
  const txt = fs.readFileSync(new URL('../src/solved.js', import.meta.url), 'utf8');
  solved = JSON.parse(txt.slice(txt.indexOf('{'), txt.lastIndexOf('}') + 1));
} catch {}

function solve(id) {
  const ops = LAYOUTS[id].map((o) => o.slice());
  const free = [];
  ops.forEach((o, i) => {
    if (o[0] === 'S') free.push({ i, k: 1, scale: 120, min: 60 });
    if (o[0] === 'T') free.push({ i, k: 1, scale: 14 });
  });
  const x0 = free.map((p) => ops[p.i][p.k]);
  const residual = (x) => {
    free.forEach((p, j) => (ops[p.i][p.k] = x[j]));
    const t = runOps(ops);
    const e = t.p;
    const yawErr = Math.atan2(t.f[0], -t.f[2]);
    const r = [e[0], e[2], e[1] * 0.3, yawErr * 600, (t.u[1] - 1) * 100];
    free.forEach((p, j) => r.push(((x[j] - x0[j]) / p.scale) * 6));
    return r;
  };
  const cost = (r) => r.reduce((a, b) => a + b * b, 0);
  let x = x0.slice();
  let lam = 10;
  const n = free.length;
  for (let it = 0; it < 300; it++) {
    const r0 = residual(x);
    const J = free.map((_, j) => {
      const xp = x.slice();
      xp[j] += 0.25;
      const rp = residual(xp);
      return rp.map((v, k) => (v - r0[k]) / 0.25);
    });
    const A = Array.from({ length: n }, (_, a) => Array.from({ length: n }, (_, b) => J[a].reduce((s, v, k) => s + v * J[b][k], 0) + (a === b ? lam : 0)));
    const M = A.map((row, i) => [...row, -J[i].reduce((s, v, k) => s + v * r0[k], 0)]);
    for (let c = 0; c < n; c++) {
      let p = c;
      for (let r = c + 1; r < n; r++) if (Math.abs(M[r][c]) > Math.abs(M[p][c])) p = r;
      [M[c], M[p]] = [M[p], M[c]];
      for (let r = c + 1; r < n; r++) {
        const f = M[r][c] / M[c][c];
        for (let k = c; k <= n; k++) M[r][k] -= f * M[c][k];
      }
    }
    const d = new Array(n);
    for (let r = n - 1; r >= 0; r--) {
      let s = M[r][n];
      for (let k = r + 1; k < n; k++) s -= M[r][k] * d[k];
      d[r] = s / M[r][r];
    }
    const xn = x.map((v, j) => (free[j].min !== undefined ? Math.max(free[j].min, v + d[j]) : v + d[j]));
    const rn = residual(xn);
    if (cost(rn) < cost(r0)) { x = xn; lam = Math.max(lam / 3, 1e-4); } else lam *= 4;
  }
  residual(x);
  const t = runOps(ops);
  const gap = Math.hypot(t.p[0], t.p[1], t.p[2]);
  console.log(id.padEnd(10), 'closure gap', gap.toFixed(2), 'yaw err(deg)', ((Math.atan2(t.f[0], -t.f[2]) * 180) / Math.PI).toFixed(3), 'length', t.len.toFixed(0));
  return ops.map((o) => o.map((v) => (typeof v === 'number' ? Math.round(v * 10) / 10 : v)));
}
for (const id of ids) solved[id] = solve(id);
fs.writeFileSync(new URL('../src/solved.js', import.meta.url), '// Generated by tools/solve-track.mjs - do not edit by hand.\nexport const SOLVED = ' + JSON.stringify(solved) + ';\n');
